version: '3.4'

services:
  nest_modular:
    container_name: nest_modular
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: /bin/sh -c "while sleep 1000; do :; done;"
    networks:
      - network1
networks:
  network1:
    name: mi_red
    external: true
